[package]
name = "openfocus"
version = "1.0.0-rc.1"
authors = ["Will Franzen <wtfranzen@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
regex = "1"
zip = "0.5.3"
xml-rs = "0.8"
chrono = "0.4"
colored = "1.9"
